# Project Information
site_name: 'rio-tiler'
site_description: 'Rasterio plugin to read mercator tiles from Cloud Optimized GeoTIFF'

docs_dir: 'docs'
site_dir: 'build'

# Repository
repo_name: 'cogeotiff/rio-tiler'
repo_url: 'https://github.com/cogeotiff/rio-tiler'
edit_uri: 'blob/master/docs/src/'
site_url: 'https://cogeotiff.github.io/rio-tiler/'

# Social links
extra:
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/cogeotiff'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/cogeotiff'
    - icon: 'fontawesome/solid/globe'
      link: 'https://www.cogeo.org/'

# Layout
nav:
  - Home: 'index.md'
  - User Guide:
    - Intro: 'intro.md'
    - COG/STAC Readers: 'readers.md'
    - Mosaic: 'mosaic.md'
    - Colormaps: 'colormap.md'
  - Advanced User Guide:
    - Working with multiple assets: 'advanced/multi_assets.md'
    - Use a Feature to read a COG: 'advanced/feature.md'
    - Create a Dynamic Tiler: 'advanced/dynamic_tiler.md'
  - Examples:
    - Mosaic: 'examples/Using-rio-tiler-mosaic.ipynb'
  - API:
    - rio_tiler.colormap: rio_tiler/colormap.md
    - rio_tiler.constants: rio_tiler/constants.md
    - rio_tiler.errors: rio_tiler/errors.md
    - rio_tiler.expression: rio_tiler/expression.md
    - rio_tiler.io:
      - rio_tiler.io.base: rio_tiler/io/base.md
      - rio_tiler.io.cogeo: rio_tiler/io/cogeo.md
      - rio_tiler.io.stac: rio_tiler/io/stac.md
    - rio_tiler.mercator: rio_tiler/mercator.md
    - rio_tiler.mosaic:
      - rio_tiler.mosaic.reader: rio_tiler/mosaic/reader.md
      - rio_tiler.mosaic.methods:
        - rio_tiler.mosaic.methods.base: rio_tiler/mosaic/methods/base.md
        - rio_tiler.mosaic.methods.defaults: rio_tiler/mosaic/methods/defaults.md
    - rio_tiler.profiles: rio_tiler/profiles.md
    - rio_tiler.reader: rio_tiler/reader.md
    - rio_tiler.tasks: rio_tiler/tasks.md
    - rio_tiler.utils: rio_tiler/utils.md
  - Migration from v1.0 to v2.0: 'v2_migration.md'
  - Development - Contributing: 'contributing.md'
  - Release Notes: 'release-notes.md'

plugins:
  - search
  - mkdocs-jupyter:
      include_source: True

# Theme
theme:
  icon:
    logo: 'material/home'
    repo: 'fontawesome/brands/github'
  name: 'material'
  language: 'en'
  palette:
    primary: 'blue'
    accent:  'light blue'
  font:
    text: 'Nunito Sans'
    code: 'Fira Code'
  custom_dir: 'docs/overrides'

# These extensions are chosen to be a superset of Pandoc's Markdown.
# This way, I can write in Pandoc's Markdown and have it be supported here.
# https://pandoc.org/MANUAL.html
markdown_extensions:
    - admonition
    - attr_list
    - codehilite:
        guess_lang: false
    - def_list
    - footnotes
    - pymdownx.arithmatex
    - pymdownx.betterem
    - pymdownx.caret:
        insert: false
    - pymdownx.details
    - pymdownx.emoji
    - pymdownx.escapeall:
        hardbreak: true
        nbsp: true
    - pymdownx.magiclink:
        hide_protocol: true
        repo_url_shortener: true
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
    - toc:
        permalink: true
